/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.tuctuc.telas;

import br.tuctuc.conexaoBancoDeDados.BD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio52699596
 */
public class CompletarCadCola extends javax.swing.JInternalFrame {

    private int idColaborador;

    public CompletarCadCola() {
        initComponents();
    }

    public CompletarCadCola(int idColaboradorAtualiza) {
        this.idColaborador = idColaboradorAtualiza;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        AreaCad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ACnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ACsituacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ACcpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ACcnpj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ACemail = new javax.swing.JTextField();
        ACgenero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ACdtcontratoinicial = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        ACcelular = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        ACusuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ACsenha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ACcnh = new javax.swing.JTextField();
        ACdtnasc = new javax.swing.JFormattedTextField();
        ACdtcnh = new javax.swing.JFormattedTextField();
        ACdtcontratofim = new javax.swing.JFormattedTextField();
        Menu = new javax.swing.JPanel();
        ACcolaborador = new javax.swing.JToggleButton();
        BTbloquear = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        BTdesbloquear = new javax.swing.JToggleButton();

        jTextField6.setText("jTextField6");

        setTitle("Atualizar cadastro de Colaborador");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        AreaCad.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nome completo");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Situação");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("CNPJ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("E-mail");

        ACgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha seu genero", "Masculino", "Feminino", " " }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Gênero");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Data Nascimento");

        try {
            ACdtcontratoinicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Celular");

        try {
            ACcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Usuário");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Senha");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("CNH");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Data vencimento CNH");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Data inicio Contrato");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Data Fim Contrato");

        try {
            ACdtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ACdtcnh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ACdtcontratofim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout AreaCadLayout = new javax.swing.GroupLayout(AreaCad);
        AreaCad.setLayout(AreaCadLayout);
        AreaCadLayout.setHorizontalGroup(
            AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaCadLayout.createSequentialGroup()
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaCadLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ACusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(AreaCadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ACsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217))
            .addGroup(AreaCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaCadLayout.createSequentialGroup()
                        .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ACnome, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AreaCadLayout.createSequentialGroup()
                                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ACcnh, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ACcpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                    .addComponent(jLabel11))
                                .addGap(38, 38, 38)
                                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)
                                    .addComponent(ACcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ACdtcnh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1)
                                .addComponent(ACsituacao)
                                .addComponent(ACgenero, 0, 213, Short.MAX_VALUE))))
                    .addComponent(jLabel5)
                    .addGroup(AreaCadLayout.createSequentialGroup()
                        .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(ACdtcontratoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(ACdtcontratofim, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ACemail, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ACcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaCadLayout.createSequentialGroup()
                    .addContainerGap(456, Short.MAX_VALUE)
                    .addComponent(ACdtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)))
        );
        AreaCadLayout.setVerticalGroup(
            AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaCadLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACcnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACdtcnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACdtcontratoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACdtcontratofim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(AreaCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AreaCadLayout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(ACdtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(342, Short.MAX_VALUE)))
        );

        Menu.setBackground(new java.awt.Color(204, 204, 204));

        ACcolaborador.setBackground(new java.awt.Color(0, 255, 51));
        ACcolaborador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ACcolaborador.setText("Atualizar Cadastro");
        ACcolaborador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ACcolaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACcolaboradorActionPerformed(evt);
            }
        });

        BTbloquear.setBackground(new java.awt.Color(255, 153, 51));
        BTbloquear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTbloquear.setText("Bloquear Usuario");
        BTbloquear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BTbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTbloquearActionPerformed(evt);
            }
        });

        jToggleButton3.setText("X");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        BTdesbloquear.setBackground(new java.awt.Color(204, 255, 0));
        BTdesbloquear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BTdesbloquear.setText("Desbloquear");
        BTdesbloquear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BTdesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTdesbloquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ACcolaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(BTbloquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTdesbloquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(ACcolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTdesbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AreaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AreaCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void ACcolaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACcolaboradorActionPerformed
// Atualizar Cadastro
        // Conectar ao banco de dados
        BD banco = new BD();
        boolean resultado = banco.conectaBD();

        // Variáveis da tela de cadastro
        String generoCl = (String) this.ACgenero.getSelectedItem();

        // String para Atualizar os dados
        String query = "UPDATE colaborador SET nome = ?, cpf = ?, cnpj = ?, cnh = ?, dtvenci_cnh = ?, email = ?, data_nascimento = ?, data_iniciocontrato = ?, data_fimcontrato = ?, genero = ?, nome_usuario = ?, situacao = ?, celular = ? WHERE id_colaborador = " + idColaborador;
        PreparedStatement ps = banco.getPreparedStatement(query);
        try {
            // Verificações para cada campo
            ps.setString(1, ACnome.getText().isEmpty() ? null : ACnome.getText());
            ps.setString(2, ACcpf.getText().isEmpty() ? null : ACcpf.getText());
            ps.setString(3, ACcnpj.getText().isEmpty() ? null : ACcnpj.getText());
            ps.setString(4, ACcnh.getText().isEmpty() ? null : ACcnh.getText());

            // Para a data de vencimento da CNH
            if (ACdtcnh.getText().isEmpty()) {
                ps.setNull(5, java.sql.Types.DATE);
            } else {
                ps.setDate(5, new java.sql.Date(new SimpleDateFormat("dd/MM/yyyy").parse(ACdtcnh.getText()).getTime()));
            }

            ps.setString(6, ACemail.getText().isEmpty() ? null : ACemail.getText());

            // Para a data de nascimento
            if (ACdtnasc.getText().isEmpty()) {
                ps.setNull(7, java.sql.Types.DATE);
            } else {
                ps.setDate(7, new java.sql.Date(new SimpleDateFormat("dd/MM/yyyy").parse(ACdtnasc.getText()).getTime()));
            }

            // Para a data de início do contrato
            if (ACdtcontratoinicial.getText().isEmpty()) {
                ps.setNull(8, java.sql.Types.DATE);
            } else {
                ps.setDate(8, new java.sql.Date(new SimpleDateFormat("dd/MM/yyyy").parse(ACdtcontratoinicial.getText()).getTime()));
            }

            // Para a data de fim do contrato
            if (ACdtcontratofim.getText().isEmpty()) {
                ps.setNull(9, java.sql.Types.DATE);
            } else {
                ps.setDate(9, new java.sql.Date(new SimpleDateFormat("dd/MM/yyyy").parse(ACdtcontratofim.getText()).getTime()));
            }

            ps.setString(10, generoCl);
            ps.setString(11, ACusuario.getText().isEmpty() ? null : ACusuario.getText());
            ps.setString(12, ACsituacao.getText().isEmpty() ? null : ACsituacao.getText());
            ps.setString(13, ACcelular.getText().isEmpty() ? null : ACcelular.getText());

            ps.execute();

            JOptionPane.showMessageDialog(this, "Cadastro Atualizado");
        } catch (SQLException | ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar no Banco de dados. Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_ACcolaboradorActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // Conectar ao banco de dados
        BD banco = new BD();
        boolean resultado = banco.conectaBD();
        if (resultado) {
            // Prepara a consulta com base no ID do cliente
            String query = "SELECT nome_usuario, cpf, celular, email, situacao FROM colaborador WHERE id_colaborador = ?";
            PreparedStatement ps = banco.getPreparedStatement(query);
            try {
                // Define o parâmetro da consulta
                ps.setInt(1, idColaborador);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    this.ACusuario.setText(rs.getString("nome_usuario"));
                    this.ACcpf.setText(rs.getString("cpf"));
                    this.ACcelular.setText(rs.getString("celular"));
                    this.ACemail.setText(rs.getString("email"));
                    this.ACsituacao.setText(rs.getString("situacao"));
                }

                rs.close();
                ps.close();
                banco.encerrarConexao();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível realizar a consulta no BD. Erro: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Erro ao conectar com o banco de dados.");
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void BTbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTbloquearActionPerformed
        // Conectar ao banco de dados
        BD banco = new BD();
        boolean resultado = banco.conectaBD();

        //String para Atualizar os dados
        try {
            // Realizar o update
            String query = "UPDATE colaborador SET situacao = 'Bloqueado' WHERE id_colaborador = " + idColaborador;
            PreparedStatement ps = banco.getPreparedStatement(query);
            ps.execute();
            ps.close();

            query = "SELECT  nome, cpf, cnpj, cnh, dtvenci_cnh, email, data_nascimento, data_iniciocontrato, data_fimcontrato, genero, nome_usuario, situacao, celular FROM colaborador WHERE id_colaborador = " + idColaborador;
            ps = banco.getPreparedStatement(query);
            // Define o parâmetro da consulta
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                this.ACnome.setText(rs.getString("nome"));
                this.ACcpf.setText(rs.getString("cpf"));
                this.ACcnpj.setText(rs.getString("cnpj"));
                this.ACcnh.setText(rs.getString("cnh"));
                this.ACdtcnh.setText(rs.getString("dtvenci_cnh"));
                this.ACemail.setText((rs.getString("email")));
                this.ACdtnasc.setText((rs.getString("data_nascimento")));
                this.ACdtcontratoinicial.setText((rs.getString("data_iniciocontrato")));
                this.ACdtcontratofim.setText((rs.getString("data_fimcontrato")));
                this.ACgenero.setSelectedItem((rs.getString("genero")));
                this.ACusuario.setText((rs.getString("nome_usuario")));
                this.ACsituacao.setText((rs.getString("situacao")));
                this.ACcelular.setText((rs.getString("celular")));

            }

            rs.close();
            ps.close();
            banco.encerrarConexao();

            JOptionPane.showMessageDialog(this, "Usuário Bloqueado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com Banco de dados. Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_BTbloquearActionPerformed

    private void BTdesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTdesbloquearActionPerformed
        // Conectar ao banco de dados
        BD banco = new BD();
        boolean resultado = banco.conectaBD();

        //String para Atualizar os dados
        try {
            // Realizar o update
            String query = "UPDATE colaborador SET situacao = 'Ativo' WHERE id_colaborador = " + idColaborador;
            PreparedStatement ps = banco.getPreparedStatement(query);
            ps.execute();
            ps.close();

            query = "SELECT  nome, cpf, cnpj, cnh, dtvenci_cnh, email, data_nascimento, data_iniciocontrato, data_fimcontrato, genero, nome_usuario, situacao, celular FROM colaborador WHERE id_colaborador = " + idColaborador;
            ps = banco.getPreparedStatement(query);
            // Define o parâmetro da consulta
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                this.ACnome.setText(rs.getString("nome"));
                this.ACcpf.setText(rs.getString("cpf"));
                this.ACcnpj.setText(rs.getString("cnpj"));
                this.ACcnh.setText(rs.getString("cnh"));
                this.ACdtcnh.setText(rs.getString("dtvenci_cnh"));
                this.ACemail.setText((rs.getString("email")));
                this.ACdtnasc.setText((rs.getString("data_nascimento")));
                this.ACdtcontratoinicial.setText((rs.getString("data_iniciocontrato")));
                this.ACdtcontratofim.setText((rs.getString("data_fimcontrato")));
                this.ACgenero.setSelectedItem((rs.getString("genero")));
                this.ACusuario.setText((rs.getString("nome_usuario")));
                this.ACsituacao.setText((rs.getString("situacao")));
                this.ACcelular.setText((rs.getString("celular")));
            }
            rs.close();
            ps.close();
            banco.encerrarConexao();

            JOptionPane.showMessageDialog(this, "Usuário Desbloquedo");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar com Banco de dados. Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_BTdesbloquearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ACcelular;
    private javax.swing.JTextField ACcnh;
    private javax.swing.JTextField ACcnpj;
    private javax.swing.JToggleButton ACcolaborador;
    private javax.swing.JTextField ACcpf;
    private javax.swing.JFormattedTextField ACdtcnh;
    private javax.swing.JFormattedTextField ACdtcontratofim;
    private javax.swing.JFormattedTextField ACdtcontratoinicial;
    private javax.swing.JFormattedTextField ACdtnasc;
    private javax.swing.JTextField ACemail;
    private javax.swing.JComboBox<String> ACgenero;
    private javax.swing.JTextField ACnome;
    private javax.swing.JTextField ACsenha;
    private javax.swing.JTextField ACsituacao;
    private javax.swing.JTextField ACusuario;
    private javax.swing.JPanel AreaCad;
    private javax.swing.JToggleButton BTbloquear;
    private javax.swing.JToggleButton BTdesbloquear;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
